POST http://localhost:3000/auth/new
content-type: application/json

{
  "name": "a",
  "email": "a@a",
  "password": "a"
}

###

POST http://localhost:3000/auth/login
content-type: application/json

{
  "email": "test1@mail.com",
  "password": "Test1!!!"
}

###
GET http://localhost:3000/facilities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHJtdC5jb20iLCJpZCI6IjY3ZWFkN2M0YzhjNTU2ZDJjNTUxZTk0NCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NTMxNjcyMCwiZXhwIjoxNzQ1MzE3NjIwfQ.frwXnvGnu6o092SJGnvzQYnYUfh3NzWcDFMUrSVs1Mk
###

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Kyle",
  "password": "password"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test1@rmt.com",
  "password": "Test1!!!"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@rmt.com",
  "password": "admin"
}

###

# reservation.time = 16:00
# tables: t6# DELAY: 90
# until 17:30, table t6 is busy
# adjust: 0 -> no busy tables
# adjust: 15 -> t6 busy table
GET http://localhost:3000/reservations/tables?date=2025-04-04&time=17:30&adjust=1facility=67ead7c4c8c556d2c551e945
Content-Type: application/json

###

GET http://localhost:3000/
Content-Type: application/json

###

GET http://localhost:3000/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHJtdC5jb20iLCJpZCI6IjY3ZWFkN2M0YzhjNTU2ZDJjNTUxZTk0NCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NTMyNTgzNCwiZXhwIjoxNzQ1MzI1ODk0fQ.D4Tsg2oPJ5pRYZhLnh6PbHAiACkrIX2qLvld8_WRTqU 

###

POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWFkN2M0YzhjNTU2ZDJjNTUxZTk0NCIsImlhdCI6MTc0NTMyNDM1MiwiZXhwIjoxNzQ1OTI5MTUyfQ.VW4qkn4NJmRDrFGY7eymsnuIPeezjKBYXa0sa9KnCeE"
}

###


###

DELETE http://localhost:3000/facilities/123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHJtdC5jb20iLCJpZCI6IjY3ZWFkN2M0YzhjNTU2ZDJjNTUxZTk0NCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NTMxNDYwNywiZXhwIjoxNzQ1MzE1NTA3fQ.8ks14W28hve72cs_MjASojNa6KWuVJ-vLRUHII5an9k