POST http://localhost:3000/auth/register
content-type: application/json

{
  "name": "a",
  "email": "a@a",
  "password": "a"
}

###

POST http://localhost:3000/auth/login
content-type: application/json

{
  "email": "test1@mail.com",
  "password": "Test1!!!"
}

###
GET http://localhost:3000/facilities?address=1&pippo=5

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Kyle",
  "password": "password"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "name": "Kyle",
  "password": "password"
}

###

# delay: 75 -> no busy tables
# delay: 90 -> t6 busy table
GET http://localhost:3000/reservations/tables?date=2025-04-04&time=17:30&adjust=15facility=67ead7c4c8c556d2c551e945
Content-Type: application/json