@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

GET http://{{host}}/test HTTP/1.1
Content-Type: {{contentType}}


###
GET http://{{host}}/api/free
Content-Type: {{contentType}}

###
GET http://{{host}}/api/free2
Content-Type: {{contentType}}

###
# @name registerAPI
POST http://{{host}}/api/auth/register
Content-Type: {{contentType}}

{
  "name": "aaa",
  "email": "test1@rmt.com",
  "password": "Test1!!!"
}

###
# @name loginAPI
POST http://{{host}}/api/auth/login
Content-Type: {{contentType}}

# {
#   "email": "admin@rmt.com",
#   "password": "admin"
# }

{
  "email": "test1@rmt.com",
  "password": "Test1!!!"
}

###

@accessToken = {{loginAPI.response.body.data.accessToken}}
@cookie = {{loginAPI.response.headers.Set-Cookie}}
###
# @name logoutAPI
DELETE http://{{host}}/api/auth/logout
Authorization: Bearer {{accessToken}}

###


GET http://{{host}}/api/free
Content-Type: {{contentType}}


###

# reservation.time = 16:00
# tables: t6# DELAY: 90
# until 17:30, table t6 is busy
# adjust: 0 -> no busy tables
# adjust: 15 -> t6 busy table
GET http://{{host}}/api/reservations/tables?date=2025-04-04&time=18:30&adjust=1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}
###

GET http://{{host}}/api/auth/whoami
Authorization: Bearer {{accessToken}}

###

GET http://{{host}}/api/token/refresh
Content-Type: {{contentType}}
Set-Cookie: {{cookie}}

###
POST http://{{host}}/api/token/revoke
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "email": "test@rmt.com"
}

###

DELETE http://{{host}}/api/facilities/123
Authorization: Bearer {{accessToken}}